global.ccr=0;
ki=4
scr(w_pl,wood,0,0,0,0,0,0,0,0)
scr(torch,stic,0,0,coal,0,0,0,0,0)
scr(stic,w_pl,w_pl,0,0,0,0,0,0,0)
scr(stic,w_pl,0,0,w_pl,0,0,0,0,0)
ki=1
scr(cr_ta,w_pl,w_pl,0,w_pl,w_pl,0,0,0,0)
scr(forge,cst,cst,cst,cst,0,cst,cst,cst,cst)
scr(chest,w_pl,w_pl,w_pl,w_pl,0,w_pl,w_pl,w_pl,w_pl)
scr(dor,w_pl,w_pl,0,w_pl,w_pl,0,w_pl,w_pl,0)
scr(nakov,ir_bl,ir_bl,ir_bl,0,iron,0,iron,iron,iron)
scr(ir_bl,iron,iron,iron,iron,iron,iron,iron,iron,iron)
scr(go_bl,gold,gold,gold,gold,gold,gold,gold,gold,gold)
scr(di_bl,diamond,diamond,diamond,diamond,diamond,diamond,diamond,diamond,diamond)
scr(re_bl,redstone,redstone,redstone,redstone,redstone,redstone,redstone,redstone,redstone)
scr(la_bl,lapis,lapis,lapis,lapis,lapis,lapis,lapis,lapis,lapis)
scr(co_bl,coal,coal,coal,coal,coal,coal,coal,coal,coal)

z=0;
stcrtools(w_pl)
stcrtools(cst)
stcrtools(iron)
stcrtools(gold)
stcrtools(diamond)
z=0;
stcrarmor(leather)
stcrarmor(gold)
stcrarmor(iron)
stcrarmor(diamond)
