k++
global.phar[k,1]=argument0
global.phar[k,2]=argument1
global.phar[k,3]=argument2
global.phar[k,4]=argument3
global.phar[k,5]=argument4
global.phar[k,6]=argument5
global.phar[k,7]=argument6
global.phar[k,8]=argument7
global.phar[k,9]=argument8
//global.phar[k,9]=argument9
